function creditos()
load logo
%scrsz = get(0,'ScreenSize');
%'Position',[scrsz(1)*220 scrsz(2)-80 scrsz(3)/2 scrsz(4)/1.6],...
h0 = figure('Color',[0.8 0.8 0.8], ...
    'MenuBar','none', ...
    'CloseRequestFcn','creditos_1(''close_acerca'')',...
    'Name','About Mult&T', ...
    'NextPlot','replacechildren', ...
    'NumberTitle','off', ...
    'Resize','off', ...
    'Position', [200   150   400   375],...
    'Tag','Fig1', ...
    'ToolBar','none');
h1 = axes('Parent',h0, ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
    'Color',[1 1 1], ...
	'DataAspectRatioMode','manual', ...
	'Layer','top', ...
	'Position',[-0.01 -0.5 1.009 2], ...
	'Tag','Axes1', ...
	'TickDir','out', ...
	'TickDirMode','manual', ...
	'Visible','off', ...
	'WarpToFill','off', ...
	'WarpToFillMode','manual', ...
	'XColor',[0 0 0], ...
	'XLim',[0.5 392.5], ...
	'XLimMode','manual', ...
	'YColor',[0 0 0], ...
	'YDir','reverse', ...
	'YLim',[0.5 374.5], ...
	'YLimMode','manual', ...
	'ZColor',[0 0 0]);
h2 = image('Parent',h1, ...
	'BusyAction','cancel', ...
	'CData',mat0, ...
	'Interruptible','off', ...
	'Tag','Axes1Image1', ...
    'visible','on',...
	'XData',[1 392], ...
	'YData',[1 374]);
h3 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','creditos_1(''credit'')', ...
	'Position',[220 7 70 18], ...
	'String','Credits', ...
	'Style','toggle', ...
	'Tag','creditos');
h31 = text(20,120,'Tools for Multivariable Control','FontName','Times New Roman',...
    'FontSize',10,'color',[200/256 50/256 10/256],'FontAngle','italic');
h4 = text(20,170,'Version 1.0 (R2009a)');
h5 = text(20,185,'January 16, 2009');
h6 = text(20,220,'License Number  : Free Distribution');
h7 = text(20,235,'University ANDES');
h8=text(20,280,'Design and Construction :','tag','text1','FontSize',8);
h9=text(20,292,'Ing. Franklin Pineda Torres.','tag','text2','FontSize',8);
h10=text(20,304,'fe.pineda92@uniandes.edu.co.','tag','text3','FontSize',8);

FigPos=get(0,'DefaultFigurePosition');
OldUnits = get(h0, 'Units');
set(h0, 'Units', 'pixels');
OldPos = get(h0,'Position');
FigWidth = OldPos(3);
FigHeight = OldPos(4);
if isempty(gcbf)
    ScreenUnits=get(0,'Units');
    set(0,'Units','pixels');
    ScreenSize=get(0,'ScreenSize');
    set(0,'Units',ScreenUnits);

    FigPos(1)=1/2*(ScreenSize(3)-FigWidth);
    FigPos(2)=2/3*(ScreenSize(4)-FigHeight);
else
    GCBFOldUnits = get(gcbf,'Units');
    set(gcbf,'Units','pixels');
    GCBFPos = get(gcbf,'Position');
    set(gcbf,'Units',GCBFOldUnits);
    FigPos(1:2) = [(GCBFPos(1) + GCBFPos(3) / 2) - FigWidth / 2, ...
                   (GCBFPos(2) + GCBFPos(4) / 2) - FigHeight / 2];
end
FigPos(3:4)=[FigWidth FigHeight];
set(h0, 'Position', FigPos);
set(h0, 'Units', OldUnits);